// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/velora-luxury/AdminDashboard.tsx": () => import("../components/mockups/velora-luxury/AdminDashboard.tsx"),
  "./components/mockups/velora-luxury/Auth.tsx": () => import("../components/mockups/velora-luxury/Auth.tsx"),
  "./components/mockups/velora-luxury/CartCheckout.tsx": () => import("../components/mockups/velora-luxury/CartCheckout.tsx"),
  "./components/mockups/velora-luxury/ContactFAQ.tsx": () => import("../components/mockups/velora-luxury/ContactFAQ.tsx"),
  "./components/mockups/velora-luxury/CustomerDashboard.tsx": () => import("../components/mockups/velora-luxury/CustomerDashboard.tsx"),
  "./components/mockups/velora-luxury/Detail.tsx": () => import("../components/mockups/velora-luxury/Detail.tsx"),
  "./components/mockups/velora-luxury/Home.tsx": () => import("../components/mockups/velora-luxury/Home.tsx"),
  "./components/mockups/velora-luxury/Listing.tsx": () => import("../components/mockups/velora-luxury/Listing.tsx"),
  "./components/mockups/velora-luxury/OrdersTracking.tsx": () => import("../components/mockups/velora-luxury/OrdersTracking.tsx"),
  "./components/mockups/velora-luxury/VendorDashboard.tsx": () => import("../components/mockups/velora-luxury/VendorDashboard.tsx")
};
