// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/velora-luxury/CartCheckout.tsx": () => import("../components/mockups/velora-luxury/CartCheckout.tsx"),
  "./components/mockups/velora-luxury/Detail.tsx": () => import("../components/mockups/velora-luxury/Detail.tsx"),
  "./components/mockups/velora-luxury/Home.tsx": () => import("../components/mockups/velora-luxury/Home.tsx"),
  "./components/mockups/velora-luxury/Listing.tsx": () => import("../components/mockups/velora-luxury/Listing.tsx")
};
