import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    /* ── Nav ── */
    "nav.home": "Home",
    "nav.shop": "Shop",
    "nav.categories": "Categories",
    "nav.login": "Login",
    "nav.register": "Register",
    "nav.dashboard": "Dashboard",
    "nav.cart": "Cart",
    "nav.search": "Search…",
    "nav.wishlist": "Wishlist",
    "nav.signedInAs": "Signed in as",
    "nav.searchPlaceholder": "Search for products, categories…",
    "nav.searchBtn": "Search",

    /* ── Buttons ── */
    "btn.logout": "Logout",
    "btn.addToCart": "Add to Cart",
    "btn.addingToCart": "Adding…",
    "btn.quickAdd": "Quick Add",
    "btn.remove": "Remove",
    "btn.clearCart": "Clear Cart",
    "btn.apply": "Apply",
    "btn.subscribe": "Subscribe",
    "btn.subscribing": "…",
    "btn.proceedToCheckout": "Proceed to Checkout",
    "btn.placeOrder": "Place Order",
    "btn.payWithPaymob": "Pay with Paymob →",
    "btn.redirectingToPaymob": "Redirecting to Paymob…",
    "btn.continueShopping": "← Continue Shopping",
    "btn.writeReview": "Write a Review",
    "btn.startShopping": "Start Shopping",
    "btn.loginToCheckout": "Login to Checkout",
    "btn.cancel": "Cancel",
    "btn.clearFilters": "Clear Filters",

    /* ── Common ── */
    "common.free": "Free",
    "common.loading": "Loading…",
    "common.page": "Page",
    "common.of": "of",
    "common.item": "item",
    "common.items": "items",
    "common.subtotal": "Subtotal",
    "common.shipping": "Shipping",
    "common.total": "Total",
    "common.discount": "Coupon discount",
    "common.color": "Color",
    "common.size": "Size",
    "common.quantity": "Quantity",
    "common.soldBy": "Sold by",
    "common.sku": "SKU",
    "common.save": "Save",
    "common.optional": "optional",
    "common.required": "required",
    "common.previous": "← Previous",
    "common.next": "Next →",
    "common.viewAll": "View All",
    "common.sale": "SALE",

    /* ── Cart ── */
    "cart.title": "Shopping Cart",
    "cart.empty": "Your Cart is Empty",
    "cart.emptyDesc": "Looks like you haven't added anything yet.",
    "cart.guestBanner": "You're browsing as a guest.",
    "cart.loginToSave": "Log in",
    "cart.loginToSaveDesc": "to save your cart and complete checkout.",
    "cart.orderSummary": "Order Summary",
    "cart.haveCoupon": "Have a coupon?",
    "cart.enterCode": "Enter code",
    "cart.applied": "applied",
    "cart.shippingFree": "Free",

    /* ── Checkout ── */
    "checkout.title": "Checkout",
    "checkout.shippingInfo": "Shipping Information",
    "checkout.firstName": "First Name",
    "checkout.lastName": "Last Name",
    "checkout.address": "Address",
    "checkout.city": "City",
    "checkout.phone": "Phone",
    "checkout.couponCode": "Coupon Code",
    "checkout.enterCoupon": "Enter coupon code",
    "checkout.paymentMethod": "Payment Method",
    "checkout.orderSummary": "Order Summary",
    "checkout.processing": "Processing…",
    "checkout.terms": "By placing your order you agree to our terms and conditions.",
    "checkout.paymobRedirect": "You'll be redirected to Paymob's secure checkout to complete payment. Your order will be confirmed after successful payment.",
    "checkout.qty": "Qty",
    "checkout.discountLabel": "Discount",
    "checkout.couponApplied": "✓ Coupon applied —",
    "checkout.off": "off",
    "checkout.successTitle": "Order placed successfully!",
    "checkout.successDesc": "We'll notify you once it ships.",
    "checkout.failTitle": "Checkout failed",
    "checkout.fillRequired": "Please fill in all required fields",

    /* ── Payment options ── */
    "payment.cod.label": "Cash on Delivery",
    "payment.cod.desc": "Pay when your order arrives",
    "payment.card.label": "Credit / Debit Card",
    "payment.card.desc": "Visa, Mastercard via Paymob",
    "payment.meeza.label": "Meeza Card",
    "payment.meeza.desc": "Egyptian national debit card via Paymob",
    "payment.vodafone.label": "Vodafone Cash",
    "payment.vodafone.desc": "Pay with your Vodafone Cash wallet",

    /* ── Products listing ── */
    "products.title": "Shop Collection",
    "products.searchPlaceholder": "Search products…",
    "products.allCategories": "All Categories",
    "products.sortBy": "Sort By",
    "products.newestFirst": "Newest First",
    "products.priceLowHigh": "Price: Low → High",
    "products.priceHighLow": "Price: High → Low",
    "products.topRated": "Top Rated",
    "products.clearFilters": "Clear filters",
    "products.search": "Search",
    "products.noProductsFound": "No products found",
    "products.noProductsYet": "No products available yet.",
    "products.tryAdjusting": "Try adjusting your search or filters.",
    "products.count_one": "product",
    "products.count_other": "products",

    /* ── Product details ── */
    "product.notFound": "Product not found",
    "product.backToShop": "Back to Shop",
    "product.home": "Home",
    "product.shop": "Shop",
    "product.zoomHint": "Click to zoom",
    "product.noImage": "No image",
    "product.selectColor": "Please select a color",
    "product.selectSize": "Please select a size",
    "product.unavailable": "This combination is not available",
    "product.selectColorFirst": "Select a color to see available sizes",
    "product.availableSizes": "of",
    "product.availableSizesLabel": "available",
    "product.save": "Save",
    "product.addedToCart": "Added to cart",
    "product.signInToSave": "Sign in to save items",
    "product.savedToWishlist": "Saved to wishlist",
    "product.removedFromWishlist": "Removed from wishlist",
    "product.freeDelivery": "Free delivery on orders over 500 EGP",
    "product.freeReturns": "Free 30-day returns on unworn items",
    "product.secureCheckout": "Secure checkout — 100% protected",
    "product.shippingTab": "Shipping",
    "product.returnsTab": "Returns & Exchanges",
    "product.shippingStandard": "Standard delivery (3–5 business days)",
    "product.shippingStandardDesc": "Free on orders over 500 EGP, otherwise 50 EGP.",
    "product.shippingExpress": "Express delivery (1–2 business days)",
    "product.shippingExpressDesc": "Available in Cairo & Giza for 80 EGP.",
    "product.shippingNote": "Orders placed before 2 PM are dispatched the same day. You'll receive an email with tracking details once your order ships.",
    "product.relatedTitle": "Related Products",
    "product.youMayAlsoLike": "You May Also Like",

    /* ── Reviews ── */
    "reviews.title": "Reviews",
    "reviews.customerFeedback": "Customer Feedback",
    "reviews.total": "reviews",
    "reviews.noReviews": "No reviews yet",
    "reviews.noReviewsDesc": "Be the first to share your experience with this product.",
    "reviews.onlyDelivered": "Only customers with delivered orders can leave a review.",
    "reviews.yourReview": "Your Review",
    "reviews.write": "Write a Review",
    "reviews.edit": "Edit Your Review",
    "reviews.rating": "Rating",
    "reviews.titleLabel": "Title",
    "reviews.commentLabel": "Comment",
    "reviews.summarize": "Summarise your experience",
    "reviews.placeholder": "Tell others what you think about this product…",
    "reviews.submit": "Submit Review",
    "reviews.update": "Update Review",
    "reviews.saving": "Saving…",
    "reviews.newestFirst": "Newest First",
    "reviews.oldestFirst": "Oldest First",
    "reviews.highestRating": "Highest Rating",
    "reviews.lowestRating": "Lowest Rating",
    "reviews.verifiedPurchase": "Verified Purchase",
    "reviews.prev": "← Prev",
    "reviews.next": "Next →",
    "reviews.pleaseRate": "Please select a rating",
    "reviews.commentMin": "Comment must be at least 10 characters",
    "reviews.submitted": "Review submitted!",
    "reviews.updated": "Review updated",
    "reviews.deleted": "Review deleted",

    /* ── Home ── */
    "home.newCollection": "New Collection",
    "home.shopNow": "Shop Now",
    "home.curatedFashion": "Curated Fashion for the Modern Minimalist",
    "home.exploreCollection": "Explore Collection",
    "home.browse": "Browse",
    "home.shopByCategory": "Shop by Category",
    "home.viewAll": "View All",
    "home.freshIn": "Fresh In",
    "home.newArrivals": "New Arrivals",
    "home.viewAllProducts": "View All Products",
    "home.mostLoved": "Most Loved",
    "home.bestSellers": "Best Sellers",
    "home.bestSellerBadge": "Best Seller",
    "home.curatedForYou": "Curated for You",
    "home.featuredCollection": "Featured Collection",
    "home.whatCustomersSay": "What Our Customers Say",
    "home.lovedByThousands": "Loved by Thousands",
    "home.reviewsSummary": "4.9/5 from 2,400+ reviews",
    "home.stayInLoop": "Stay in the Loop",
    "home.joinCommunity": "Join the LUXE Community",
    "home.newsletterDesc": "Get early access to new arrivals, exclusive offers, and style inspiration delivered to your inbox.",
    "home.enterEmail": "Enter your email",
    "home.subscribed": "🎉 You're on the list! Welcome to LUXE.",
    "home.faq": "Frequently Asked Questions",
    "home.viewAllFaqs": "View all FAQs →",
    "home.quickView": "Quick View",
    "home.saleBadge": "SALE",
    "home.faqQ1": "How long does shipping take?",
    "home.faqA1": "Standard delivery takes 3-5 business days within Egypt. Express options are available at checkout.",
    "home.faqQ2": "What is your return policy?",
    "home.faqA2": "We offer a 30-day return policy on all unworn items with original tags attached.",
    "home.faqQ3": "Do you accept Cash on Delivery?",
    "home.faqA3": "Yes! We accept Cash on Delivery (COD) across Egypt, as well as card payments via Paymob.",
    /* Trust items */
    "home.trust.freeShipping": "Free Shipping",
    "home.trust.freeShippingDesc": "On orders over 500 EGP",
    "home.trust.easyReturns": "Easy Returns",
    "home.trust.easyReturnsDesc": "30-day return policy",
    "home.trust.securePayment": "Secure Payment",
    "home.trust.securePaymentDesc": "100% protected checkout",
    "home.trust.multiplePayment": "Multiple Payment",
    "home.trust.multiplePaymentDesc": "Card, Meeza & Cash",
    /* Testimonials */
    "home.t1.name": "Sara A.",
    "home.t1.text": "Absolutely love the quality. The fabric is so soft and the fit is perfect. Will definitely order again!",
    "home.t1.location": "Cairo",
    "home.t2.name": "Mona K.",
    "home.t2.text": "Fast delivery and beautiful packaging. LUXE feels like a truly premium brand experience.",
    "home.t2.location": "Alexandria",
    "home.t3.name": "Layla M.",
    "home.t3.text": "The best online fashion store in Egypt. Stylish, high quality and great customer service.",
    "home.t3.location": "Giza",

    /* ── Auth ── */
    "auth.welcomeBack": "Welcome back to LUXE",
    "auth.joinCommunity": "Join the LUXE community",
    "auth.orWithEmail": "Or continue with email",
    "auth.orRegisterWithEmail": "Or register with email",
    "auth.email": "Email",
    "auth.emailPlaceholder": "Enter your email",
    "auth.password": "Password",
    "auth.passwordPlaceholder": "Enter your password",
    "auth.newPasswordPlaceholder": "Create a password (min. 6 characters)",
    "auth.confirmPassword": "Confirm Password",
    "auth.confirmPasswordPlaceholder": "Re-enter your password",
    "auth.fullName": "Full Name",
    "auth.fullNamePlaceholder": "Enter your full name",
    "auth.accountType": "Account Type",
    "auth.accountTypePlaceholder": "Select account type",
    "auth.customer": "Customer",
    "auth.customerDesc": "— Browse & shop",
    "auth.vendor": "Vendor",
    "auth.vendorDesc": "— Sell on LUXE",
    "auth.forgotPassword": "Forgot password?",
    "auth.dontHaveAccount": "Don't have an account?",
    "auth.alreadyHaveAccount": "Already have an account?",
    "auth.rememberDevice": "Remember this device",
    "auth.rememberDeviceDesc": "Skip new-device security alerts when signing in from this browser. Uncheck on shared or public computers.",
    "auth.signingIn": "Signing in…",
    "auth.creatingAccount": "Creating account…",
    "auth.loginSuccess": "Welcome back!",
    "auth.loginSuccessDesc": "Signed in as",
    "auth.loginFailed": "Login failed",
    "auth.loginError": "Invalid email or password",
    "auth.registerSuccess": "Welcome to LUXE!",
    "auth.registerSuccessDesc": "Your account has been created.",
    "auth.registerFailed": "Registration failed",

    /* ── Footer ── */
    "footer.tagline": "Premium fashion marketplace bringing you the finest curated collections from top vendors worldwide.",
    "footer.shop": "Shop",
    "footer.allProducts": "All Products",
    "footer.categories": "Categories",
    "footer.featured": "Featured",
    "footer.about": "About Us",
    "footer.support": "Support",
    "footer.contactUs": "Contact Us",
    "footer.faq": "FAQ",
    "footer.returns": "Returns & Exchanges",
    "footer.shippingPolicy": "Shipping Policy",
    "footer.legal": "Legal",
    "footer.privacyPolicy": "Privacy Policy",
    "footer.terms": "Terms & Conditions",
    "footer.newsletter": "Newsletter",
    "footer.newsletterDesc": "Subscribe for exclusive deals and updates.",
    "footer.emailPlaceholder": "your@email.com",
    "footer.subscribe": "Subscribe",
    "footer.subscribing": "…",
    "footer.allRightsReserved": "All rights reserved.",
    "footer.privacy": "Privacy",
    "footer.termsShort": "Terms",
    "footer.alreadySubscribed": "Already subscribed!",
    "footer.alreadySubscribedDesc": "This email is already on our list.",
    "footer.subscribeSuccess": "Successfully subscribed!",
    "footer.subscribeSuccessDesc": "Thank you for subscribing to our newsletter.",
    "footer.subscribeError": "Something went wrong",
  },

  ar: {
    /* ── Nav ── */
    "nav.home": "الرئيسية",
    "nav.shop": "المتجر",
    "nav.categories": "الفئات",
    "nav.login": "تسجيل الدخول",
    "nav.register": "إنشاء حساب",
    "nav.dashboard": "لوحة التحكم",
    "nav.cart": "عربة التسوق",
    "nav.search": "بحث…",
    "nav.wishlist": "المفضلة",
    "nav.signedInAs": "مسجل الدخول كـ",
    "nav.searchPlaceholder": "ابحث عن منتجات وفئات…",
    "nav.searchBtn": "بحث",

    /* ── Buttons ── */
    "btn.logout": "تسجيل خروج",
    "btn.addToCart": "أضف إلى السلة",
    "btn.addingToCart": "جاري الإضافة…",
    "btn.quickAdd": "إضافة سريعة",
    "btn.remove": "حذف",
    "btn.clearCart": "إفراغ السلة",
    "btn.apply": "تطبيق",
    "btn.subscribe": "اشترك",
    "btn.subscribing": "…",
    "btn.proceedToCheckout": "إتمام الشراء",
    "btn.placeOrder": "تأكيد الطلب",
    "btn.payWithPaymob": "الدفع عبر Paymob ←",
    "btn.redirectingToPaymob": "جاري التحويل إلى Paymob…",
    "btn.continueShopping": "→ متابعة التسوق",
    "btn.writeReview": "كتابة تقييم",
    "btn.startShopping": "ابدأ التسوق",
    "btn.loginToCheckout": "تسجيل الدخول للشراء",
    "btn.cancel": "إلغاء",
    "btn.clearFilters": "مسح الفلاتر",

    /* ── Common ── */
    "common.free": "مجاني",
    "common.loading": "جاري التحميل…",
    "common.page": "صفحة",
    "common.of": "من",
    "common.item": "عنصر",
    "common.items": "عناصر",
    "common.subtotal": "المجموع الجزئي",
    "common.shipping": "الشحن",
    "common.total": "الإجمالي",
    "common.discount": "خصم الكوبون",
    "common.color": "اللون",
    "common.size": "الحجم",
    "common.quantity": "الكمية",
    "common.soldBy": "تباع بواسطة",
    "common.sku": "رمز المنتج",
    "common.save": "وفر",
    "common.optional": "اختياري",
    "common.required": "مطلوب",
    "common.previous": "→ السابق",
    "common.next": "التالي ←",
    "common.viewAll": "عرض الكل",
    "common.sale": "تخفيض",

    /* ── Cart ── */
    "cart.title": "عربة التسوق",
    "cart.empty": "سلتك فارغة",
    "cart.emptyDesc": "لم تضف أي منتجات بعد.",
    "cart.guestBanner": "أنت تتصفح كضيف.",
    "cart.loginToSave": "سجل دخولك",
    "cart.loginToSaveDesc": "لحفظ سلتك وإتمام الشراء.",
    "cart.orderSummary": "ملخص الطلب",
    "cart.haveCoupon": "هل لديك كوبون؟",
    "cart.enterCode": "أدخل الكود",
    "cart.applied": "مُطبَّق",
    "cart.shippingFree": "مجاني",

    /* ── Checkout ── */
    "checkout.title": "إتمام الشراء",
    "checkout.shippingInfo": "معلومات الشحن",
    "checkout.firstName": "الاسم الأول",
    "checkout.lastName": "اسم العائلة",
    "checkout.address": "العنوان",
    "checkout.city": "المدينة",
    "checkout.phone": "رقم الهاتف",
    "checkout.couponCode": "كوبون الخصم",
    "checkout.enterCoupon": "أدخل كود الكوبون",
    "checkout.paymentMethod": "طريقة الدفع",
    "checkout.orderSummary": "ملخص الطلب",
    "checkout.processing": "جاري المعالجة…",
    "checkout.terms": "بتأكيد طلبك فأنت توافق على الشروط والأحكام.",
    "checkout.paymobRedirect": "ستُحوَّل إلى صفحة الدفع الآمنة عبر Paymob. سيتم تأكيد طلبك بعد إتمام الدفع.",
    "checkout.qty": "الكمية",
    "checkout.discountLabel": "الخصم",
    "checkout.couponApplied": "✓ تم تطبيق الكوبون —",
    "checkout.off": "خصم",
    "checkout.successTitle": "تم تأكيد الطلب!",
    "checkout.successDesc": "سنُعلمك عند الشحن.",
    "checkout.failTitle": "فشل إتمام الشراء",
    "checkout.fillRequired": "يرجى ملء جميع الحقول المطلوبة",

    /* ── Payment options ── */
    "payment.cod.label": "الدفع عند الاستلام",
    "payment.cod.desc": "ادفع عند وصول طلبك",
    "payment.card.label": "بطاقة ائتمان / خصم",
    "payment.card.desc": "فيزا وماستركارد عبر Paymob",
    "payment.meeza.label": "بطاقة ميزة",
    "payment.meeza.desc": "بطاقة الخصم الوطنية المصرية عبر Paymob",
    "payment.vodafone.label": "فودافون كاش",
    "payment.vodafone.desc": "ادفع بمحفظة فودافون كاش",

    /* ── Products listing ── */
    "products.title": "تشكيلة المتجر",
    "products.searchPlaceholder": "ابحث عن منتجات…",
    "products.allCategories": "جميع الفئات",
    "products.sortBy": "ترتيب حسب",
    "products.newestFirst": "الأحدث أولاً",
    "products.priceLowHigh": "السعر: من الأقل للأعلى",
    "products.priceHighLow": "السعر: من الأعلى للأقل",
    "products.topRated": "الأعلى تقييماً",
    "products.clearFilters": "مسح الفلاتر",
    "products.search": "بحث",
    "products.noProductsFound": "لا توجد منتجات",
    "products.noProductsYet": "لا توجد منتجات متاحة بعد.",
    "products.tryAdjusting": "جرب تعديل البحث أو الفلاتر.",
    "products.count_one": "منتج",
    "products.count_other": "منتجات",

    /* ── Product details ── */
    "product.notFound": "المنتج غير موجود",
    "product.backToShop": "العودة إلى المتجر",
    "product.home": "الرئيسية",
    "product.shop": "المتجر",
    "product.zoomHint": "انقر للتكبير",
    "product.noImage": "لا توجد صورة",
    "product.selectColor": "يرجى اختيار اللون",
    "product.selectSize": "يرجى اختيار المقاس",
    "product.unavailable": "هذا التوليف غير متاح",
    "product.selectColorFirst": "اختر لوناً لرؤية المقاسات المتاحة",
    "product.availableSizes": "من",
    "product.availableSizesLabel": "متاح",
    "product.save": "وفر",
    "product.addedToCart": "أُضيف إلى السلة",
    "product.signInToSave": "سجل دخولك لحفظ المنتجات",
    "product.savedToWishlist": "أُضيف إلى المفضلة",
    "product.removedFromWishlist": "أُزيل من المفضلة",
    "product.freeDelivery": "توصيل مجاني للطلبات فوق ٥٠٠ جنيه",
    "product.freeReturns": "إرجاع مجاني خلال ٣٠ يوماً للمنتجات غير المستخدمة",
    "product.secureCheckout": "دفع آمن — محمي بالكامل",
    "product.shippingTab": "الشحن",
    "product.returnsTab": "الإرجاع والاستبدال",
    "product.shippingStandard": "التوصيل العادي (٣–٥ أيام عمل)",
    "product.shippingStandardDesc": "مجاني للطلبات فوق ٥٠٠ جنيه، وإلا ٥٠ جنيه.",
    "product.shippingExpress": "التوصيل السريع (١–٢ يوم عمل)",
    "product.shippingExpressDesc": "متاح في القاهرة والجيزة بـ ٨٠ جنيه.",
    "product.shippingNote": "الطلبات قبل الساعة ٢ ظهراً ترسَل في نفس اليوم. ستصلك رسالة بتفاصيل التتبع عند الشحن.",
    "product.relatedTitle": "منتجات ذات صلة",
    "product.youMayAlsoLike": "قد يعجبك أيضاً",

    /* ── Reviews ── */
    "reviews.title": "التقييمات",
    "reviews.customerFeedback": "آراء العملاء",
    "reviews.total": "تقييم",
    "reviews.noReviews": "لا توجد تقييمات بعد",
    "reviews.noReviewsDesc": "كن أول من يشارك تجربته مع هذا المنتج.",
    "reviews.onlyDelivered": "يمكن فقط للعملاء الذين استلموا طلباتهم إضافة تقييم.",
    "reviews.yourReview": "تقييمك",
    "reviews.write": "كتابة تقييم",
    "reviews.edit": "تعديل تقييمك",
    "reviews.rating": "التقييم",
    "reviews.titleLabel": "العنوان",
    "reviews.commentLabel": "التعليق",
    "reviews.summarize": "لخّص تجربتك",
    "reviews.placeholder": "شارك رأيك في هذا المنتج…",
    "reviews.submit": "إرسال التقييم",
    "reviews.update": "تحديث التقييم",
    "reviews.saving": "جاري الحفظ…",
    "reviews.newestFirst": "الأحدث أولاً",
    "reviews.oldestFirst": "الأقدم أولاً",
    "reviews.highestRating": "الأعلى تقييماً",
    "reviews.lowestRating": "الأدنى تقييماً",
    "reviews.verifiedPurchase": "مشتري موثق",
    "reviews.prev": "→ السابق",
    "reviews.next": "التالي ←",
    "reviews.pleaseRate": "يرجى اختيار تقييم",
    "reviews.commentMin": "يجب أن يكون التعليق ١٠ أحرف على الأقل",
    "reviews.submitted": "تم إرسال التقييم!",
    "reviews.updated": "تم تحديث التقييم",
    "reviews.deleted": "تم حذف التقييم",

    /* ── Home ── */
    "home.newCollection": "مجموعة جديدة",
    "home.shopNow": "تسوق الآن",
    "home.curatedFashion": "أزياء راقية للأناقة العصرية",
    "home.exploreCollection": "استكشف المجموعة",
    "home.browse": "تصفح",
    "home.shopByCategory": "تسوق حسب الفئة",
    "home.viewAll": "عرض الكل",
    "home.freshIn": "وصل حديثاً",
    "home.newArrivals": "وصل حديثاً",
    "home.viewAllProducts": "عرض كل المنتجات",
    "home.mostLoved": "الأكثر شعبية",
    "home.bestSellers": "الأكثر مبيعاً",
    "home.bestSellerBadge": "الأكثر مبيعاً",
    "home.curatedForYou": "مختارة لك",
    "home.featuredCollection": "المجموعة المميزة",
    "home.whatCustomersSay": "ماذا يقول عملاؤنا",
    "home.lovedByThousands": "يحبه الآلاف",
    "home.reviewsSummary": "٤.٩/٥ من أكثر من ٢٤٠٠ تقييم",
    "home.stayInLoop": "ابق على اطلاع",
    "home.joinCommunity": "انضم لمجتمع LUXE",
    "home.newsletterDesc": "احصل على وصول مبكر للمجموعات الجديدة وعروض حصرية مباشرة في بريدك.",
    "home.enterEmail": "أدخل بريدك الإلكتروني",
    "home.subscribed": "🎉 أنت الآن في القائمة! أهلاً بك في LUXE.",
    "home.faq": "الأسئلة الشائعة",
    "home.viewAllFaqs": "عرض كل الأسئلة ←",
    "home.quickView": "عرض سريع",
    "home.saleBadge": "تخفيض",
    "home.faqQ1": "كم يستغرق الشحن؟",
    "home.faqA1": "يستغرق التوصيل العادي ٣-٥ أيام عمل داخل مصر. خيارات التوصيل السريع متاحة عند الشراء.",
    "home.faqQ2": "ما سياسة الإرجاع؟",
    "home.faqA2": "نوفر سياسة إرجاع ٣٠ يوماً لجميع المنتجات غير المستخدمة مع بطاقات السعر الأصلية.",
    "home.faqQ3": "هل تقبلون الدفع عند الاستلام؟",
    "home.faqA3": "نعم! نقبل الدفع عند الاستلام في جميع أنحاء مصر، وكذلك الدفع بالبطاقة عبر Paymob.",
    /* Trust items */
    "home.trust.freeShipping": "شحن مجاني",
    "home.trust.freeShippingDesc": "للطلبات فوق ٥٠٠ جنيه",
    "home.trust.easyReturns": "إرجاع سهل",
    "home.trust.easyReturnsDesc": "سياسة إرجاع ٣٠ يوماً",
    "home.trust.securePayment": "دفع آمن",
    "home.trust.securePaymentDesc": "دفع محمي ١٠٠٪",
    "home.trust.multiplePayment": "طرق دفع متعددة",
    "home.trust.multiplePaymentDesc": "بطاقة وميزة وكاش",
    /* Testimonials */
    "home.t1.name": "سارة أ.",
    "home.t1.text": "أحب الجودة كثيراً. القماش ناعم جداً والمقاس مثالي. سأطلب مرة أخرى!",
    "home.t1.location": "القاهرة",
    "home.t2.name": "منى ك.",
    "home.t2.text": "توصيل سريع وتغليف جميل. LUXE تبدو علامة تجارية راقية حقاً.",
    "home.t2.location": "الإسكندرية",
    "home.t3.name": "ليلى م.",
    "home.t3.text": "أفضل متجر أزياء إلكتروني في مصر. أنيق وعالي الجودة وخدمة عملاء رائعة.",
    "home.t3.location": "الجيزة",

    /* ── Auth ── */
    "auth.welcomeBack": "أهلاً بعودتك إلى LUXE",
    "auth.joinCommunity": "انضم إلى مجتمع LUXE",
    "auth.orWithEmail": "أو تابع بالبريد الإلكتروني",
    "auth.orRegisterWithEmail": "أو سجل بالبريد الإلكتروني",
    "auth.email": "البريد الإلكتروني",
    "auth.emailPlaceholder": "أدخل بريدك الإلكتروني",
    "auth.password": "كلمة المرور",
    "auth.passwordPlaceholder": "أدخل كلمة المرور",
    "auth.newPasswordPlaceholder": "أنشئ كلمة مرور (٦ أحرف على الأقل)",
    "auth.confirmPassword": "تأكيد كلمة المرور",
    "auth.confirmPasswordPlaceholder": "أعد إدخال كلمة المرور",
    "auth.fullName": "الاسم الكامل",
    "auth.fullNamePlaceholder": "أدخل اسمك الكامل",
    "auth.accountType": "نوع الحساب",
    "auth.accountTypePlaceholder": "اختر نوع الحساب",
    "auth.customer": "عميل",
    "auth.customerDesc": "— تصفح وتسوق",
    "auth.vendor": "بائع",
    "auth.vendorDesc": "— بِع على LUXE",
    "auth.forgotPassword": "نسيت كلمة المرور؟",
    "auth.dontHaveAccount": "ليس لديك حساب؟",
    "auth.alreadyHaveAccount": "لديك حساب بالفعل؟",
    "auth.rememberDevice": "تذكر هذا الجهاز",
    "auth.rememberDeviceDesc": "تجاوز تنبيهات الأجهزة الجديدة عند تسجيل الدخول من هذا المتصفح. ألغِ التحديد على الأجهزة المشتركة.",
    "auth.signingIn": "جاري تسجيل الدخول…",
    "auth.creatingAccount": "جاري إنشاء الحساب…",
    "auth.loginSuccess": "أهلاً بعودتك!",
    "auth.loginSuccessDesc": "تم تسجيل الدخول كـ",
    "auth.loginFailed": "فشل تسجيل الدخول",
    "auth.loginError": "البريد الإلكتروني أو كلمة المرور غير صحيحة",
    "auth.registerSuccess": "أهلاً بك في LUXE!",
    "auth.registerSuccessDesc": "تم إنشاء حسابك.",
    "auth.registerFailed": "فشل إنشاء الحساب",

    /* ── Footer ── */
    "footer.tagline": "منصة أزياء راقية تجمع أفضل الماركات والمصممين من جميع أنحاء العالم.",
    "footer.shop": "تسوق",
    "footer.allProducts": "جميع المنتجات",
    "footer.categories": "الفئات",
    "footer.featured": "المميز",
    "footer.about": "من نحن",
    "footer.support": "دعم",
    "footer.contactUs": "تواصل معنا",
    "footer.faq": "الأسئلة الشائعة",
    "footer.returns": "الإرجاع والاستبدال",
    "footer.shippingPolicy": "سياسة الشحن",
    "footer.legal": "قانوني",
    "footer.privacyPolicy": "سياسة الخصوصية",
    "footer.terms": "الشروط والأحكام",
    "footer.newsletter": "النشرة الإخبارية",
    "footer.newsletterDesc": "اشترك للحصول على العروض الحصرية.",
    "footer.emailPlaceholder": "بريدك الإلكتروني",
    "footer.subscribe": "اشترك",
    "footer.subscribing": "…",
    "footer.allRightsReserved": "جميع الحقوق محفوظة.",
    "footer.privacy": "الخصوصية",
    "footer.termsShort": "الشروط",
    "footer.alreadySubscribed": "أنت مشترك بالفعل!",
    "footer.alreadySubscribedDesc": "بريدك الإلكتروني مسجل بالفعل.",
    "footer.subscribeSuccess": "تم الاشتراك بنجاح!",
    "footer.subscribeSuccessDesc": "شكراً لاشتراكك في نشرتنا الإخبارية.",
    "footer.subscribeError": "حدث خطأ",
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem("language");
    return (stored === "ar" || stored === "en") ? stored : "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  useEffect(() => {
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] ?? translations["en"][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

export function useTranslation() {
  return useLanguage();
}
