import { pgTable, serial, text, timestamp } from "drizzle-orm/pg-core";

export const storeSettingsTable = pgTable("store_settings", {
  id: serial("id").primaryKey(),
  key: text("key").notNull().unique(),
  value: text("value"),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export type StoreSetting = typeof storeSettingsTable.$inferSelect;

export const DEFAULT_SETTINGS: Record<string, string> = {
  store_name: "Velora",
  store_name_ar: "لوكس",
  store_logo: "",
  contact_email: "",
  contact_phone: "",
  contact_address: "",
  contact_address_ar: "",
  social_facebook: "",
  social_instagram: "",
  social_twitter: "",
  social_tiktok: "",
  social_youtube: "",
  email_from_name: "Velora Store",
  email_from_address: "",
  payment_cod_enabled: "true",
  payment_paymob_enabled: "false",
  paymob_iframe_id: "",
  paymob_integration_id_card: "",
  paymob_integration_id_meeza: "",
  paymob_integration_id_vodafone: "",
  shipping_free_threshold: "500",
  shipping_fee: "50",
  seo_title: "Velora — Premium Fashion",
  seo_description: "Discover the latest in luxury fashion. Shop premium clothing, accessories, and more.",
  seo_keywords: "fashion, luxury, clothing, accessories",
  homepage_show_banners: "true",
  homepage_show_featured: "true",
  homepage_show_new_arrivals: "true",
  homepage_show_best_sellers: "true",
  homepage_show_categories: "true",
  google_client_id: "",
  whatsapp_enabled: "false",
  whatsapp_provider: "cloud",
  whatsapp_template_order_placed: "order_placed",
  whatsapp_template_payment_approved: "payment_approved",
  whatsapp_template_order_shipped: "order_shipped",
  whatsapp_template_order_delivered: "order_delivered",
  whatsapp_template_support_reply: "support_reply",
  abandoned_cart_enabled: "true",
  abandoned_cart_threshold_hours: "1",
  payment_vodafone_cash_enabled: "false",
  payment_etisalat_cash_enabled: "false",
  payment_instapay_enabled: "false",
  vodafone_cash_number: "",
  etisalat_cash_number: "",
  instapay_address: "",
};
